networks:
  knative-network:

services:
  frontend:
    image: knative-group/frontend
    container_name: knative-group-frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync+restart
          path: ./frontend
          target: /app
    networks:
      - knative-network

  api-gateway:
    image: knative-group/api-gateway
    container_name: knative-group-api-gateway
    build:
      context: ./server/api-gateway
      dockerfile: ./Dockerfile
    command: go run main.go
    develop:
      watch:
        - action: sync+restart
          path: ./server/api-gateway
          target: /app
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - knative-network

  bookstore-api-comments-svc:
    image: knative-group/comments
    container_name: knative-group-comments
    build:
      context: ./server/comments
      dockerfile: ./Dockerfile
    command: go run main.go
    develop:
      watch:
        - action: sync+restart
          path: ./server/comments
          target: /app
    restart: unless-stopped
    networks:
      - knative-network
  
  bookstore-api-likes-svc:
    image: knative-group/likes
    container_name: knative-group-likes
    build:
      context: ./server/likes
      dockerfile: ./Dockerfile
    command: go run main.go
    develop:
      watch:
        - action: sync+restart
          path: ./server/likes
          target: /app
    restart: unless-stopped
    networks:
      - knative-network